[connections.snowflake]
connection_name = "snowflake"
account = "DHWSDST.ZXA46192"
user = "jytbrd"
password = "Snow2023flake"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "JAMF_DEVICE_INFO"
schema = "public"
client_session_keep_alive = true
